name: Creating Java flow

on:
  push:
    branches:
      - main

jobs:
  java-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Check Java Version
        run: java -version

      - name: Compile Java File
        run: javac App.java

      - name: Run Java Application
        run: java app
