name: Creating Java flow

on:
  push: 
    branches: 
      -main

jobs:
  java-demo:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v4

      - name: Setup Java enviroment
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-verion: '17'
      - name: Check Java Version
        run: java -version

      - name: Compile java file
        run: javac app.java

      - name: Run Java Application
        run: java app.java
    
